// Automatically generated.
// Refer to rollup.config.js and script/yaml2dts.py for the relevant logic.

export interface UiText {
    Econox: "Econox" | "에코녹스";
    FeatureHub: "Feature Hub" | "피처 허브";
    Console: "Console" | "콘솔";
    SignInOut: "Sign In/Out" | "로그인/회원가입";
    Login: "Login" | "로그인";
    Logout: "Logout" | "로그아웃";
    Signup: "Signup" | "회원가입";
    Email: "Email" | "이메일";
    Password: "Password" | "비밀번호";
    RetypePassword: "Retype password" | "비밀번호 확인";
    LoginInfoIncorrect: "Email or password is incorrect" | "이메일 또는 비밀번호가 올바르지 않습니다";
    UnexpectedError: "An unexpected error has occurred" | "예기치 못한 오류가 발생했습니다";
    Ok: "OK" | "확인";
    Close: "Close" | "닫기";
    Submit: "Submit" | "확인";
    RetypePasswordMismatch: "Passwords do not match" | "비밀번호가 일치하지 않습니다";
    UserAlreadyExists: "This email is already registered" | "이미 가입되어있는 이메일입니다";
    IncorrectPasswordLength: "Password must be at least 6 characters long" | "비밀번호는 6글자 이상이어야 합니다";
    PleaseEnterEmailConfirmCode: "Please enter the verification code sent to your email" | "이메일로 전송된 인증 코드를 입력해주세요";
    ConfirmCodeAlreadyExpired: "The code you received has already expired" | "전송된 인증 코드는 이미 만료되었습니다";
    ConfirmCodeExpired: "Verification code has expired" | "인증 코드가 만료되었습니다";
    ConfirmCodeMismatch: "Verification code is incorrect" | "인증 코드가 올바르지 않습니다";
    Next: "Next" | "다음";
    Membership: "Membership" | "맴버십";
    SelectMembership: "Select Membership" | "맴버십 선택";
    SelectMembershipSubtitle: "New members receive their chosen membership free for the first month with no charge!" | "첫 회원가입 고객을 대상으로 선택한 맴버십이 첫 한달간 결제 없이 무료로 제공됩니다!";
    ChangeMembership: "Change Membership" | "맴버십 변경";
    BasicPlan: "Basic" | "일반";
    BasicPlanDollerPrice: "$9.99/month" | "$9.99/월";
    BasicPlanWonPrice: "₩11,900/month" | "11,900원/월";
    BasicPlanDescription: "Discover causality by comparing time-series from global markets, economies, and corporate data.  Grasp the macroeconomy at a glance and gain crucial investment insights." | "전세계 금융시장, 국가경제, 기업데이터 시계열을 비교해서 선후관계를 발견하세요.  거시경제를 한눈에 파악하고 투자에 필요한 통찰을 얻을 수 있습니다.";
    ProfessionalPlan: "Professional" | "전문가";
    ProfessionalPlanDollerPrice: "$12.99/month" | "$12.99/월";
    ProfessionalPlanWonPrice: "₩15,900/month" | "15,900원/월";
    ProfessionalPlanDescription: "Download all data without any limits!" | "모든 데이터를 무제한으로 다운로드 할 수 있습니다!";
    PhoneConfirmReason: "Phone verification is required to determine if you are eligible for the new member benefits" | "최초 회원가입 혜택 대상자 여부를 확인하기 위해 전화번호 인증이 필요합니다";
    EnterPhoneNumber: "Enter Phone Number" | "전화번호 입력";
    SendVerificationCode: "Send Verification Code" | "인증코드 발송";
    Country: "Country" | "국가";
    PhoneConfirmCodeSendFailed: "Failed to send verification code. Please check if the phone number entered is correct" | "인증번호 전송에 실패하였습니다. 입력한 전화번호가 올바른지 확인해주세요";
    PleaseEnterPhoneNumber: "Please enter your phone number" | "전화번호를 입력해주세요";
    PleaseEnterPhoneConfirmCode: "Please enter the verification code sent via text message" | "문자 메세지로 전송된 인증코드를 입력해주세요";
    InsufficientInput: "There are missing values" | "누락된 값이 있습니다";
    EmailInputIncorrect: "Unable to proceed with email verification. Please enter a valid email" | "이메일 인증을 진행할 수 없습니다. 올바른 이메일을 입력해주세요";
    TooManyRequests: "Too many requests detected. Please try again later" | "너무 많은 요청이 감지되었습니다. 나중에 다시 시도하세요";
    ConfirmCodeSended: "Verification code has been sent" | "인증 코드가 전송되었습니다";
    SignupComplete: "Signup is complete" | "회원가입이 완료되었습니다";
    BenefitExplanation: "Enjoy your first month of membership for free as part of our new member benefits!  After that, you'll be asked to enter your payment details, and your monthly subscription fee will apply" | "최초 회원가입 혜택으로 첫 달 맴버십이 무료로 제공됩니다!  혜택 종료 후 결제수단 등록으로 안내되며 매달 맴버십 금액이 청구됩니다";
    EmailConfirmIncompleted: "Email verification is not yet completed" | "이메일 인증이 완료되지 않았습니다";
    UnusualSignupRequest: "This is not a valid signup request" | "정상적인 회원가입 요청이 아닙니다";
    EmailFormatIncorrect: "The email format is not valid" | "이메일 형식이 올바르지 않습니다";
    ResendConfirmCode: "Resend Code" | "코드 재전송";
    NoBenefitPleasePayment: "You are not eligible for the new member benefits. Please enter your payment information" | "첫 회원가입 혜택 대상자가 아닙니다. 결제 정보를 입력해주세요";
    PaymentInfoIncorrect: "The payment information is not valid. Please re-enter" | "결제 정보가 올바르지 않습니다 다시 입력해주세요";
    CreditCardNumber: "Credit Card Number" | "결제 카드 번호";
    ExpiryDate: "Expiry Date" | "유효기간";
    CardType: "Card Type" | "카드 종류";
    Card_Personal: "Personal" | "개인";
    Card_Business: "Business" | "사업자";
    BirthDate: "Date of Birth" | "생년월일";
    BusinessNumber: "Business Number" | "사업자등록번호";
    ClickLogin_for_SignupComplete: "Click the 'Login' button to complete your signup" | "로그인 버튼을 눌러 회원가입을 완료하세요";
    Name: "Name" | "이름";
    PaymentMethod: "Payment Method" | "결제 수단";
    AccountInfo: "Account Dashboard" | "계정 정보";
    ChangePassword: "Change Password" | "비밀번호 변경";
    PaymentHistory: "Payment History" | "결제 내역";
    Change: "Update" | "변경하기";
    Cancel: "Cancel" | "취소";
    EnterNewName: "Enter the new name" | "새로운 이름을 입력하세요";
    EnterNewPassword: "Enter the new password" | "새로운 비밀번호를 입력하세요";
    PasswordChangeSuccessful: "Your password has been updated. Please log in with your new password" | "비밀번호가 재설정되었습니다. 새로운 비밀번호로 로그인하세요";
    ForgotPassword: "Forgot Password?" | "비밀번호를 잊으셨나요?";
    ForgotPassword_EnterEmail: "Enter the email address of the account you wish to retrieve" | "찾고자 하는 계정의 이메일 주소를 입력하세요";
    ConfirmCode: "Verification Code" | "인증 코드";
    NewPassword: "New Password" | "새로운 비밀번호";
    UserDoesNotExist: "No user exists with the provided email" | "해당 이메일로 등록된 사용자가 존재하지 않습니다";
    InvalidInput: "Invalid input" | "입력값이 잘못되었습니다";
    PaymentMethod_Waiting: "Waiting... May take up to 30 minutes" | "결제수단 확인중... 최대 30분 소요됨";
    PaymentMethod_Benefit: "New Member Benefit Applied" | "첫 회원가입 혜택 적용중";
    PaymentMethod_ChangeNotAllow_DueDate: "No changes allowed on due date" | "결제 예정일에는 변경할 수 없습니다";
    PaymentMethod_ChangeNotAllow_Waiting: "No changes allowed while payment method is being verified. Please try again in a moment" | "결제수단 확인 중에는 변경할 수 없습니다 잠시 후 다시 시도해주세요";
    PaymentMethod_ChangeCompleted: "Done! We've successfully changed your payment method" | "결제수단이 변경되었습니다";
    PaymentMethod_Change: "Update Payment Method" | "결제수단 변경";
    PaymentMethod_EnterNewCard: "Please enter your new card details to update your payment information." | "새롭게 등록할 카드 정보를 입력해주세요";
    PaymentMethod_Benefit_ChangeAlert: "Since the New Member Benefit is active, there is no need to register a payment method" | "첫 회원가입 혜택이 적용중이므로 결제수단 등록이 필요하지 않습니다";
    PaymentHistoryLimit: "Only the last 15 payment transactions will be displayed" | "결제 내역은 최근 15건까지만 표시됩니다";
    AlreadyProgressPleaseWait: "Your request is already in progress. Please wait a moment" | "요청이 이미 처리 중입니다. 잠시만 기다려주세요";
    StopBilling: "Stop Billing" | "결제 중단";
    StopBillingComplete: "Billing has been halted. Due to a failed charge on the next billing date, your account will be deactivated" | "결제가 중단되었습니다. 다음 결제일에 결제가 실패하며 계정이 비활성화됩니다";
    BillingActivationComplete: "Billing has been halted. Due to a failed charge on the next billing date, your account will be deactivated" | "결제가 활성화되었습니다";
    AccountDeactiveScheduled: "Billing has been paused. Your account will be deactivated on the next billing date" | "결제가 정지되었습니다. 다음 결제일에 계정이 비활성화됩니다";
    BillingActivation: "Billing Activate" | "결제 활성화";
    AccountActivation: "Account Activate" | "계정 활성화";
    DeleteAccount: "Delete Account" | "즉시 탈퇴";
    AccountStatusActive: "Account status: Active" | "계정 상태가 정상입니다";
    AccountStatusDeactive: "Account status: Deactive" | "계정이 비활성 상태입니다";
    ConnotStopPayment: "You have no registered payment method" | "등록된 결제수단이 존재하지 않습니다";
    f_AutoLoginTimer: "You will be automatically logged in after {time} seconds" | "{time}초 후 자동으로 로그인됩니다";
    f_NextBillingDate: "The next payment date is {m}/{d}/{y}" | "다음 결제일은 {y}년 {m}월 {d}일입니다";
    f_KRW: "₩{v}" | "{v}원";
    f_USD: "${v}";
    f_LengthLimit: "You cannot enter more than {v} characters" | "{v}글자 이상 입력할 수 없습니다";
    f_ForgotPassword_EnterNewPassword: "We've sent a code to {email}. Please enter it along with your new password" | "인증코드가 {email}에 전송되었습니다. 해당 코드와 함께 새로운 비밀번호를 입력해주세요";
    f_AlreadyAppliedMembership: "You are already enrolled in the {membership} membership" | "{membership} 맴버십은 이미 적용되어있습니다.";
    f_MembershipChangeComplete: "Your membership has been changed from {oldMembership} to {newMembership}. Due to the price difference, your next billing date has been adjusted from {oldBillingDate} to {newBillingDate}." | "맴버십이 {oldMembership}에서 {newMembership}(으)로 변경되었으며, 차액이 적용되어 다음 결제 날짜가 {oldBillingDate} 에서 {newBillingDate} 로 조정되었습니다.";
    f_MembershipChangeComplete_Benefit: "Your membership has been updated from {oldMembership} to {newMembership}" | "맴버십이 {oldMembership}에서 {newMembership}(으)로 변경되었습니다";
}