export const introBottomText = {
  en: [
    "Stock market",
    "Forex market",
    "Cryptocurrency market",
    "Commodity prices",
    "Investor positions",
    "Number of employees in a company",
    "Operating profit of a company",
    "Capital and debt of a company",
    "Detailed cash flow of a company",
    "Detailed operating expenses of a company",
    "Credit rating data of a company",
    "Cash flow statement of a company",
    "Balance sheet of a company",
    "Income statement of a company",
    "Financial growth rate of a company",
    "ESG data of a company",
    "Futures market investor positions",
    "Pre-tax total income of a company",
    "Fixed assets and current assets of a company",
  ],
  ko: [
    "주식 시장",
    "외환 시장",
    "암호화폐 시장",
    "원자재 가격",
    "투자자 포지션",
    "기업의 직원 수",
    "기업의 영업 이익",
    "기업의 자본과 부채",
    "기업의 상세 현금 흐름",
    "기업의 상세 운영 비용",
    "기업의 신용 평가 데이터",
    "기업의 현금흐름표",
    "기업의 대차대조표",
    "기업의 손익계산서",
    "기업의 재무 성장률",
    "기업의 ESG 데이터",
    "선물 시장 투자자 포지션",
    "기업의 법인세 차감 전 종합 소득",
    "기업의 부동자산과 유동자산",
  ],
};
