export const introBottomText = {
  en: [
    "Stock market",
    "Forex market",
    "Cryptocurrency market",
    "Commodity prices",
    "Investor positions",
    "Number of employees in a company",
    "Operating profit of a company",
    "Capital and debt of a company",
    "Detailed cash flow of a company",
    "Detailed operating expenses of a company",
    "Credit rating data of a company",
    "Cash flow statement of a company",
    "Balance sheet of a company",
    "Income statement of a company",
    "Financial growth rate of a company",
    "ESG data of a company",
    "Futures market investor positions",
    "Pre-tax total income of a company",
    "Fixed assets and current assets of a company",
  ],
  ko: [
    "주식 시장",
    "외환 시장",
    "암호화폐 시장",
    "원자재 가격",
    "투자자 포지션",
    "기업의 직원 수",
    "기업의 영업 이익",
    "기업의 자본과 부채",
    "기업의 상세 현금 흐름",
    "기업의 상세 운영 비용",
    "기업의 신용 평가 데이터",
    "기업의 현금흐름표",
    "기업의 대차대조표",
    "기업의 손익계산서",
    "기업의 재무 성장률",
    "기업의 ESG 데이터",
    "선물 시장 투자자 포지션",
    "기업의 법인세 차감 전 종합 소득",
    "기업의 부동자산과 유동자산",
  ],
};

export const footerText = {
  en: [
    "Business Reg. No. 312-23-12342 | E-Commerce Reg. 2312-SeoulGangnam-01142",
    "CEO: Won JeongHoo | Phone: 010-7528-7237 | Email: clomia@econox.io",
    "Business Address: 13, Jeongui-ro 7-gil, Songpa-gu, Seoul, Republic of Korea A 1803",
    "Terms of Use / Privacy Policy",
  ],
  ko: [
    "사업자등록번호: 312-23-12342 | 통신판매신고: 제2312-서울강남-01142호",
    "대표: 원정후 | 전화번호: 010-7528-7237 | 이메일: clomia@econox.io",
    "소재지: 서울특별시 송파구 정의로 7길 힐스테이트에코송파 A동 1803호",
    "이용약관 / 개인정보처리방침",
  ],
};
