from client.world_bank.data_metaclass import ClientMeta


class Trade(metaclass=ClientMeta):
    name = "Trade"
    note = "Statistics regarding a country's commercial exchange with the world"

    cur_balance = "BN.CAB.XOKA.GD.ZS"
    exp_growth = "NE.EXP.GNFS.KD.ZG"
    exp_ratio = "NE.EXP.GNFS.ZS"
    imp_growth = "NE.IMP.GNFS.KD.ZG"
    imp_ratio = "NE.IMP.GNFS.ZS"
    trade_dep = "TG.VAL.TOTL.GD.ZS"
    unit_imp_price_change = "TM.UVI.MRCH.XD.WD"
    total_imp_price_change = "TM.VAL.MRCH.XD.WD"
    trade_cond_index = "TT.PRI.MRCH.XD.WD"
    exp_unit_index = "TX.UVI.MRCH.XD.WD"
    it_exp_ratio = "TX.VAL.ICTG.ZS.UN"
    exp_val_index = "TX.VAL.MRCH.XD.WD"


class Natural(metaclass=ClientMeta):
    name = "Natural"
    note = "Indicators representing the environmental conditions and energy usage"

    forest_area_ratio = "AG.LND.FRST.ZS"
    green_power_ratio = "EG.ELC.RNEW.ZS"
    green_elec_usage = "EG.FEC.RNEW.ZS"
    co2_emission = "EN.ATM.CO2E.PC"
    air_pollution = "EN.ATM.PM25.MC.M3"
    poll_exposed_pop = "EN.ATM.PM25.MC.ZS"


class Population(metaclass=ClientMeta):
    name = "Population"
    note = "Demographic data including education, mortality, and employment statistics"

    elem_entry_rate = "SE.PRM.ENRR"
    mid_entry_rate = "SE.SEC.ENRR"
    female_legis_ratio = "SG.GEN.PARL.ZS"
    infant_death_rate = "SH.DYN.MORT"
    female_lab_part = "SL.TLF.CACT.FM.ZS"
    total_lab_part = "SL.TLF.CACT.ZS"
    unemp_rate = "SL.UEM.TOTL.ZS"
    refugee_pop = "SM.POP.REFG.OR"
    teen_birth_rate = "SP.ADO.TFRT"
    birth_rate = "SP.DYN.CBRT.IN"
    death_rate = "SP.DYN.CDRT.IN"
    female_life_exp = "SP.DYN.LE00.FE.IN"
    male_life_exp = "SP.DYN.LE00.MA.IN"
    female_births = "SP.DYN.TFRT.IN"
    old_pop_ratio = "SP.POP.DPND.OL"
    young_pop_ratio = "SP.POP.DPND.YG"
    pop_growth_rate = "SP.POP.GROW"
    total_pop = "SP.POP.TOTL"


class Industry(metaclass=ClientMeta):
    name = "Industry"
    note = "Metrics related to production, infrastructure, and technological progress"

    agri_land = "AG.LND.AGRI.ZS"
    cereal_land = "AG.LND.CREL.HA"
    cereal_yield = "AG.YLD.CREL.KG"
    organic_access = "EG.CFT.ACCS.ZS"
    energy_ineff = "EG.EGY.PRIM.PP.KD"
    rural_elec_access = "EG.ELC.ACCS.RU.ZS"
    urban_elec_access = "EG.ELC.ACCS.UR.ZS"
    total_elec_access = "EG.ELC.ACCS.ZS"
    com_bank_count = "FB.CBK.BRCH.P5"
    elec_supply_time = "IC.ELC.TIME"
    startup_time = "IC.REG.DURS"
    sci_articles = "IP.JRN.ARTC.SC"
    mobile_subs = "IT.CEL.SETS.P2"
    internet_users = "IT.NET.USER.ZS"
    value_per_agri_worker = "NV.AGR.EMPL.KD"
    agri_value_growth = "NV.AGR.TOTL.KD.ZG"
    agri_value_ratio = "NV.AGR.TOTL.ZS"
    value_per_ind_worker = "NV.IND.EMPL.KD"
    manu_value_growth = "NV.IND.MANF.KD.ZG"
    ind_value_growth = "NV.IND.TOTL.KD.ZG"
    ind_value_ratio = "NV.IND.TOTL.ZS"
    value_per_serv_worker = "NV.SRV.EMPL.KD"
    serv_value_growth = "NV.SRV.TOTL.KD.ZG"
    serv_value_ratio = "NV.SRV.TOTL.ZS"
    natural_res_ratio = "NY.GDP.TOTL.RT.ZS"
    agri_empl_rate = "SL.AGR.EMPL.ZS"
    total_empl_rate = "SL.EMP.TOTL.SP.ZS"
    ind_empl_rate = "SL.IND.EMPL.ZS"
    serv_empl_rate = "SL.SRV.EMPL.ZS"
    tourism_income_rate = "ST.INT.RCPT.XP.ZS"
    tourism_expend_rate = "ST.INT.XPND.MP.ZS"


class Economy(metaclass=ClientMeta):
    name = "Economy"
    note = "Measures of a country's economic performance and financial transactions"

    foreign_invest = "BX.KLT.DINV.CD.WD"
    foreign_invest_gdp = "BX.KLT.DINV.WD.GD.ZS"
    portfolio_inflow = "BX.PEF.TOTL.CD.WD"
    personal_remitt = "BX.TRF.PWKR.CD.DT"
    personal_remitt_gdp = "BX.TRF.PWKR.DT.GD.ZS"
    cpi = "FP.CPI.TOTL"
    income_tax = "IC.TAX.PRFT.CP.ZS"
    tax_ratio = "IC.TAX.TOTL.CP.ZS"
    consump_growth = "NE.CON.TOTL.KD.ZG"
    consump_ratio = "NE.CON.TOTL.ZS"
    cap_invest_growth = "NE.GDI.TOTL.KD.ZG"
    cap_invest_ratio = "NE.GDI.TOTL.ZS"
    adj_net_savings = "NY.ADJ.SVNG.GN.ZS"
    gdp = "NY.GDP.MKTP.CD"
    gdp_growth = "NY.GDP.MKTP.KD.ZG"
    gni_ppp = "NY.GNP.PCAP.CD"
    gni_atlas = "NY.GNP.PCAP.PP.CD"
    savings_ratio = "NY.GNS.ICTR.ZS"
    gdp_per_emp = "SL.GDP.PCAP.EM.KD"
    gni = "NY.GNP.ATLS.CD"
